"use client";

import { useState } from "react";

type Variant = "operational" | "wealth" | "travel" | "portfolio";

const copy: Record<Variant, [string, string]> = {
  operational: ["Dashboard", "Your private action center"],
  wealth: ["Wealth", "Accounts, loans, and one balance"],
  travel: ["Travel", "Routes watched quietly"],
  portfolio: ["Investments", "Holdings you've entered, priced for you"],
};

const actions = [
  ["🧾", "Bill tracked", "Electricity · due 28 Oct", "Approve"],
  ["📅", "Calendar change", "Dentist · review before saving", "Review"],
  ["✓", "Task prepared", "Call the landlord · tomorrow", "Approve"],
];

const moduleLabels: Record<Variant, string> = {
  operational: "Base · Operational",
  wealth: "Wealth · Finance",
  travel: "Travel",
  portfolio: "Wealth · Investments",
};

function ActivityBars() {
  return <div className="mt-3 flex h-12 items-end gap-1" role="img" aria-label="Illustrative activity over the last seven days">{[34, 48, 42, 70, 58, 86, 62, 74].map((height, i) => <span key={i} className="flex-1 rounded-t-sm bg-green/75" style={{ height: `${height}%` }} />)}</div>;
}

export default function CommercialAppPreview({ variant }: { variant: Variant }) {
  const [title, eyebrow] = copy[variant];
  const [resolved, setResolved] = useState<Record<string, string>>({});
  const resolve = (label: string, outcome: string) => setResolved((current) => current[label] ? current : { ...current, [label]: outcome });
  return <div className="grain relative overflow-hidden rounded-2xl border border-border-strong bg-bg-card shadow-[0_40px_120px_-30px_rgba(0,0,0,0.7)]">
    <div className="flex flex-wrap items-center gap-2 border-b border-border px-4 py-3"><span className="grid h-6 w-6 place-items-center rounded-md bg-green text-xs font-bold text-white">✓</span><span className="text-[10px] text-text-tertiary">SafePersonalAI</span><span className="text-text-tertiary">·</span><span className="text-xs font-medium text-text">{title}</span><span className="ml-auto rounded-full border border-border px-2 py-0.5 text-[9px] text-text-tertiary">Illustrative preview</span></div>
    <div className="grid grid-cols-[92px_1fr] sm:grid-cols-[116px_1fr] max-[520px]:grid-cols-1"><aside aria-label={`${title} illustrative navigation`} className="border-r border-border bg-bg-raised/60 p-3 max-[520px]:flex max-[520px]:items-center max-[520px]:gap-2 max-[520px]:overflow-x-auto max-[520px]:border-r-0 max-[520px]:border-b max-[520px]:py-2"><div className="mb-5 grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-green text-xs font-bold text-white max-[520px]:mb-0">✓</div>{["Dashboard", "Settings", "Custom Rules", "To-Dos"].map((label, i) => <div key={label} className={`mb-1 shrink-0 rounded-lg px-2 py-2 text-[10px] ${i === 0 ? "bg-green/12 font-semibold text-green" : "text-text-tertiary"} max-[520px]:mb-0`}>{label}</div>)}<div className="mt-5 border-t border-border pt-3 text-[9px] uppercase tracking-[.12em] text-text-tertiary max-[520px]:mt-0 max-[520px]:border-l max-[520px]:border-t-0 max-[520px]:pl-2">Modules</div><div className="mt-2 space-y-1.5 text-[10px] text-text-secondary max-[520px]:mt-0 max-[520px]:flex max-[520px]:items-center max-[520px]:gap-2"><div className={`shrink-0 ${variant === "operational" ? "rounded-md bg-green/12 px-1.5 py-1 font-semibold text-green" : ""}`}>Base {variant === "operational" ? <span>Ready</span> : <span>Included</span>}</div><div className={`shrink-0 ${variant === "wealth" || variant === "portfolio" ? "rounded-md bg-green/12 px-1.5 py-1 font-semibold text-green" : "opacity-60"}`}>Wealth {variant === "wealth" || variant === "portfolio" ? <span>Preview</span> : <span>🔒</span>}</div><div className={`shrink-0 ${variant === "travel" ? "rounded-md bg-violet/12 px-1.5 py-1 font-semibold text-violet" : "opacity-60"}`}>Travel {variant === "travel" ? <span>Preview</span> : <span>🔒</span>}</div></div></aside>
      <main className="min-w-0 p-3 sm:p-4"><div className="mb-3 flex items-center justify-between gap-2"><div><p className="text-[10px] text-text-tertiary">{moduleLabels[variant]} · {eyebrow}</p><p className="mt-0.5 text-sm font-semibold text-text">Good morning</p></div><span className="rounded-full border border-green/25 bg-green/10 px-2 py-1 text-[9px] text-green">On this Mac</span></div>
        <div className="grid grid-cols-3 gap-2">{[["Awaiting review", variant === "operational" ? "3" : "0"], ["Activity this week", "12"], ["License", variant === "operational" ? "Active" : "Locked"]].map(([label, value]) => <div key={label} className="rounded-xl border border-border bg-bg-raised p-2.5"><p className="text-[9px] text-text-tertiary">{label}</p><p className="mt-1 text-base font-semibold text-text">{value}</p></div>)}</div>
        <div className="mt-3 rounded-xl border border-border bg-bg-raised p-3"><div className="flex items-center justify-between"><div><p className="text-[11px] font-semibold text-text">Activity at a glance</p><p className="text-[9px] text-text-tertiary">Illustrative · last 7 days</p></div><span className="rounded-full border border-border px-2 py-1 text-[9px] text-text-tertiary">Week</span></div><ActivityBars /><div className="mt-2 flex justify-between text-[9px] text-text-tertiary"><span><b className="text-text">12</b> prepared</span><span><b className="text-text">3</b> awaiting</span><span><b className="text-text">1</b> attention</span></div></div>
        {variant === "operational" && <><div className="mt-3 rounded-xl border border-border bg-bg-raised p-3"><div className="flex items-center justify-between"><p className="text-[11px] font-semibold text-text">Pending Actions</p><span className="text-[9px] text-green">{actions.length - Object.keys(resolved).length} awaiting review</span></div><div className="mt-2 space-y-1.5">{actions.map(([icon, t, d, cta]) => { const outcome = resolved[t]; return <div key={t} className="flex flex-wrap items-center gap-2 rounded-lg border border-border px-2 py-2"><span aria-hidden="true" className="text-xs">{icon}</span><div className="min-w-0 flex-1"><p className="truncate text-[10px] font-medium text-text">{t}</p><p className="truncate text-[9px] text-text-tertiary">{d}</p></div>{outcome ? <span className="rounded-full bg-green/10 px-1.5 py-1 text-[8px] font-semibold text-green" aria-live="polite">{outcome}</span> : <div className="flex shrink-0 items-center gap-1"><button type="button" onClick={() => resolve(t, "Rejected locally")} className="rounded-md border border-border-strong px-1.5 py-1 text-[8px] text-text-tertiary transition hover:border-red/50 hover:text-red focus-visible:outline-2 focus-visible:outline-green focus-visible:outline-offset-2" aria-label={`Reject illustrative ${t}`}>Reject</button><button type="button" onClick={() => resolve(t, `${cta === "Review" ? "Reviewed" : "Approved"} locally`)} className="rounded-md bg-green px-1.5 py-1 text-[8px] font-semibold text-white transition hover:brightness-110 focus-visible:outline-2 focus-visible:outline-green focus-visible:outline-offset-2" aria-label={`${cta} illustrative ${t}`}>{cta}</button></div>}</div>; })}</div></div><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-xl border border-border bg-bg-raised px-3 py-2"><p className="text-[9px] text-text-tertiary">Connected sources</p><p className="mt-1 text-[10px] font-semibold text-text">Mail.app · iMessage</p></div><div className="rounded-xl border border-border bg-bg-raised px-3 py-2"><p className="text-[9px] text-text-tertiary">Output</p><p className="mt-1 text-[10px] font-semibold text-text">English · EUR</p></div></div><div className="mt-3 flex items-center gap-2 rounded-xl border border-green/25 bg-green/10 px-3 py-2 text-[9px] text-text-secondary"><span className="h-1.5 w-1.5 rounded-full bg-green" />These wait for your OK.</div></>}
        {variant === "wealth" && <div className="mt-3 space-y-2"><div className="rounded-xl border border-border bg-bg-raised p-3"><div className="flex items-center justify-between"><p className="text-[11px] font-semibold text-text">Wealth balance</p><span className="text-[9px] text-text-tertiary">Every account, combined</span></div><p className="mt-2 text-xl font-semibold text-text">€12,480.50</p></div><div className="rounded-xl border border-border bg-bg-raised p-3"><div className="flex items-center justify-between"><p className="text-[10px] font-medium text-text">Kitchen loan</p><span className="rounded-full border border-green/25 bg-green/10 px-2 py-0.5 text-[8px] text-green">Solved: payment</span></div><p className="mt-1 text-[9px] text-text-tertiary">€8,000 · 4.2% · 36 months</p><p className="mt-1 text-sm font-semibold text-text">€237.14 <span className="text-[9px] font-normal text-text-tertiary">/ month</span></p></div><div className="flex items-center gap-2 rounded-xl border border-border bg-bg-raised px-3 py-2 text-[9px] text-text-secondary"><span aria-hidden="true">🏦</span> Deutsche Bank tagged — link a CSV import to this account anytime.</div></div>}
        {variant === "travel" && <div className="mt-3 space-y-2"><div className="rounded-xl border border-violet/25 bg-violet/10 px-3 py-2 text-[9px] text-text-secondary">SerpApi quota, your own key <span className="float-right font-semibold text-violet">42 / 245 used</span></div>{[["Berlin → Lisbon", "€128", "Deal"], ["Hamburg → Barcelona", "€179", "Watching"], ["Munich → Athens", "€151", "Deal"]].map(([route, price, state]) => <div key={route} className="flex items-center justify-between rounded-xl border border-border bg-bg-raised px-3 py-2.5"><div><p className="text-[10px] font-medium text-text">{route}</p><p className="text-[9px] text-text-tertiary">Checked automatically, once a day</p></div><div className="text-right"><p className={`text-xs font-semibold ${state === "Deal" ? "text-green" : "text-text"}`}>{price}</p><p className="text-[9px] text-text-tertiary">{state}</p></div></div>)}</div>}
        {variant === "portfolio" && <div className="mt-3 space-y-2">{[["Gold", "12.5 g · bought €68.20/g", "€71.40/g"], ["Acme Corp shares", "40 · bought €22.10", "€24.85"]].map(([label, basis, live]) => <div key={label} className="rounded-xl border border-border bg-bg-raised px-3 py-2.5"><div className="flex items-center justify-between"><p className="text-[10px] font-medium text-text">{label}</p><p className="text-xs font-semibold text-green">{live}</p></div><p className="text-[9px] text-text-tertiary">{basis}</p></div>)}<div className="flex items-center gap-2 rounded-xl border border-border bg-bg-raised px-3 py-2 text-[9px] text-text-secondary"><span aria-hidden="true">📄</span> Or import a CSV — any bank or broker, mapped once.</div></div>}
        {variant !== "operational" && <div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-xl border border-border bg-bg-raised px-3 py-2"><p className="text-[9px] text-text-tertiary">Connected sources</p><p className="mt-1 text-[10px] font-semibold text-text">Mail.app · iMessage</p></div><div className="rounded-xl border border-border bg-bg-raised px-3 py-2"><p className="text-[9px] text-text-tertiary">Output</p><p className="mt-1 text-[10px] font-semibold text-text">English · EUR</p></div></div>}
        <div className="mt-3 flex items-center justify-between text-[9px] text-text-tertiary"><span>Last synced just now</span><span>Refresh ↻</span></div>
        {variant !== "operational" && <div className="mt-3 flex items-start gap-2 rounded-xl border border-green/25 bg-green/10 px-3 py-2 text-[9px] text-text-secondary"><span aria-hidden="true" className="mt-0.5 h-1.5 w-1.5 shrink-0 rounded-full bg-green" /><span><strong className="font-semibold text-text">Add-on preview.</strong> This module unlocks with its one-time license. Nothing is sent, purchased, or changed without your approval.</span></div>}
        <div className="mt-3 flex items-center justify-between rounded-xl border border-border bg-bg-raised px-3 py-2 text-[9px] text-text-secondary"><span><span aria-hidden="true">🛡️</span> Trust Center</span><span className="text-green">Access checked on this Mac</span></div>
      </main></div>
  </div>;
}
